import type { OpportunityCategory } from "./types";

export const ALL_CATEGORIES: OpportunityCategory[] = [
  "Remote Part-Time Jobs",
  "Freelance Work",
  "Virtual Assistant",
  "Data Entry",
  "Customer Service",
  "Social Media Management",
  "Affiliate Marketing",
  "Online Tutoring",
  "Content Writing",
  "Graphic Design",
  "Website Testing",
  "User Testing",
  "Transcription",
  "AI-Related Freelance Work",
  "Digital Products",
  "Print-on-Demand",
  "Online Surveys",
  "Microtasks",
  "Delivery / Driving",
  "Weekend Work",
  "Evening Jobs",
  "Temporary Work",
  "Consulting",
  "Administrative Work",
  "Automotive Side Jobs",
  "Remote Jobs",
  "Other",
];
